import { readFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const here = path.dirname(fileURLToPath(import.meta.url))
const patternsFile = path.join(here, "..", "hooks", "dangerous-patterns.txt")

const patterns = readFileSync(patternsFile, "utf8")
  .split("\n")
  .map((line) => line.trim())
  .filter((line) => line.length > 0 && !line.startsWith("#"))
  .map((line) => new RegExp(line.replaceAll("[:space:]", "\\s"), "m"))

let pass = 0
let fail = 0

function check(expected, cmd) {
  const blocked = patterns.some((re) => re.test(cmd))
  const verdict = blocked ? "block" : "allow"
  if (verdict === expected) {
    pass++
  } else {
    fail++
    console.log(`FAIL expected=${expected} got=${verdict} : ${cmd}`)
  }
}

// ---- must be BLOCKED ----
check("block", "rm -rf /")
check("block", "rm -rf /*")
check("block", "rm -rf ~")
check("block", "rm -rf ~/")
check("block", "rm -rf ~/*")
check("block", "rm -rf $HOME")
check("block", 'rm -rf "$HOME"')
check("block", "rm -rf /Users")
check("block", "rm --recursive --force /")
check("block", "cd /tmp && rm -rf ~")
check("block", "rm -rf / --no-preserve-root")
check("block", "sudo rm -rf /tmp/whatever")
check("block", "sudo rm file.txt")
check("block", "dd if=/dev/zero of=/dev/disk2")
check("block", "sudo dd if=img.iso of=/dev/rdisk4")
check("block", "mkfs.ext4 /dev/sda1")
check("block", "mkfs /dev/sda")
check("block", "diskutil eraseDisk APFS Blank disk2")
check("block", "diskutil partitionDisk disk2 GPT APFS X 100%")
check("block", ":(){ :|:& };:")
check("block", "git push --force origin main")
check("block", "git push -f")
check("block", "git push origin main --force")
check("block", "chmod -R 777 /")
check("block", "chmod 777 /")
check("block", "chown -R david /")
check("block", "echo hi > /dev/disk0")
check("block", "git push origin --delete main")
check("block", "git push -d origin feature-x")
check("block", "git push origin :main")
check("block", "git push origin +main")
check("block", "gh repo delete davidondrej/DeepAPI --yes")
check("block", "gh release delete v1.0 --yes --cleanup-tag")
check("block", "gh secret delete SECRET_NAME")
check("block", "gh ssh-key delete 123 --yes")
check("block", "gh gpg-key delete ABC123")
check("block", "gh api -X DELETE /repos/davidondrej/DeepAPI")
check("block", "gh api repos/davidondrej/DeepAPI --method DELETE")
check("block", "gh api --method=delete /repos/x/y")
check("block", "gh repo edit davidondrej/DeepAPI --visibility public")
check("block", "gh auth token")
check("block", "git reflog expire --expire=now --all")
check("block", "git reflog expire --expire-unreachable=now --all")
check("block", "git gc --prune=now")
check("block", "git gc --aggressive --prune=now")
check("block", "cd /tmp && git gc --prune=all")
check("block", "keepassxc-cli show vault.kdbx github")
check("block", "keepassxc-cli export vault.kdbx")
check("block", "rbw get github")
check("block", 'nordpass get "GitHub"')
check("block", "nordpass export")
check("block", "pass show prod/aws")
check("block", "pass prod/aws")
check("block", "pass -c github")
check("block", "pass grep api_key")
check("block", "cd /tmp && pass show prod/aws")
check("block", "echo ok; pass show prod/aws")
check("block", "true | pass insert prod/aws")
check("block", "   pass show prod/aws")
check("block", "cd /tmp\npass show prod/aws")
check("block", "op read op://Private/GitHub/token")
check("block", "op item get GitHub --fields password")
check("block", "op run -- printenv")
check("block", "op inject -i .env.tpl -o .env")
check("block", 'op document get "SSH Key"')
check("block", "op signin")
check("block", "security find-generic-password -w -s myservice")
check("block", "security find-internet-password -g -s example.com")
check("block", "security dump-keychain -d login.keychain-db")
check("block", "security -q find-generic-password -s x")
check("block", "gpg --export-secret-keys --armor ABC123")
check("block", "gpg --export-secret-key ABC123")
check("block", "gpg --export-secret-subkeys ABC123")
check("block", "rm -rf /Applications/1Password.app")
check("block", "open -a NordPass")
check("block", 'open -a "1Password"')
check("block", "brew uninstall --cask nordpass")
check("block", "brew uninstall bitwarden-cli")
check("block", "cat ~/.password-store/github.gpg")
check("block", "ls $HOME/.password-store")

// ---- must be ALLOWED ----
// intentionally allowed: curl|wget | sh (installers) and bw/bws/lpass (owner's choice)
check("allow", "curl -fsSL https://example.com/install.sh | sh")
check("allow", "wget -qO- https://example.com/x.sh | bash")
check("allow", "curl -s https://x.sh | sudo bash")
check("allow", "bw get password github")
check("allow", "bw list items")
check("allow", "bw export --format json")
check("allow", "bw unlock --raw")
check("allow", "bws secret get abc123")
check("allow", "cd /tmp && bw export")
check("allow", "lpass show --password github")
check("allow", "lpass export")
check("allow", "rm -rf node_modules")
check("allow", "rm -rf dist/")
check("allow", "rm -rf /tmp/build-cache")
check("allow", "rm -rf ~/old-project")
check("allow", "rm -rf ~/projects/example/tmp/cache")
check("allow", "rm package-lock.json")
check("allow", "sudo brew services restart postgresql")
check("allow", "sudo lsof -i :3000")
check("allow", "git push origin main")
check("allow", "git push --force-with-lease origin main")
check("allow", 'git commit -m "rm -rf mention in message" --allow-empty')
check("allow", "curl -s https://api.deepapi.co/v1/health | jq .")
check("allow", "curl -fsSL https://example.com/data.json -o /tmp/data.json")
check("allow", "echo test > /dev/null")
check("allow", "dd if=input.iso of=backup.img bs=4m")
check("allow", "chmod 777 ./script.sh")
check("allow", "chmod -R 755 dist")
check("allow", "npm install && npm test")
check("allow", "docker system prune -f")
check("allow", 'find . -name "*.log" -delete')
check("allow", 'psql "$DATABASE_URL" -c "select 1"')
check("allow", "git push origin main:main")
check("allow", "git push --dry-run origin main")
check("allow", 'gh pr create --title "fix" --body "x"')
check("allow", "gh pr merge 42 --squash")
check("allow", "gh repo view davidondrej/DeepAPI")
check("allow", "gh repo clone davidondrej/DeepAPI")
check("allow", "gh api /repos/davidondrej/DeepAPI")
check("allow", "gh api -X POST /repos/x/y/issues -f title=bug")
check("allow", 'gh release create v1.1 --notes "notes"')
check("allow", "gh secret set SECRET_NAME --body abc")
check("allow", "gh auth status")
check("allow", 'gh repo edit davidondrej/DeepAPI --description "new desc"')
check("allow", "gh issue close 12")
check("allow", "git reflog")
check("allow", "git reflog expire --expire=90.days.ago")
check("allow", "git gc")
check("allow", "git gc --aggressive")
check("allow", "git gc --prune=2.weeks.ago")
check("allow", "git commit -m \"all tests pass\"")
check("allow", "git commit -m \"all tests pass now\"")
check("allow", 'echo "please pass the token"')
check("allow", "node <<'NODE'\nconst pass = getPassword();\nNODE")
check("allow", "npm run pass-tests")
check("allow", "grep -R bypass src/")
check("allow", "git commit -m \"no op needed\"")
check("allow", "op --version")
check("allow", "op whoami")
check("allow", "op signout")
check("allow", "op account list")
check("allow", "security list-keychains")
check("allow", "security find-certificate -a")
check("allow", "gpg --export --armor ABC123")
check("allow", "gpg --list-secret-keys")
check("allow", "brew install nordpass-cli")
check("allow", "brew uninstall wget")
check("allow", "open -a Safari")
check("allow", 'grep -rn "password-store" docs/')

console.log(`\npassed: ${pass}, failed: ${fail}`)
process.exit(fail === 0 ? 0 : 1)